#!/bin/bash

LAST_WORKING_DIR=~/.config/clitoolkit/last_working_dir

# Common
open /Applications/Dropbox.app
pkill TogglDesktop  # The beta version needs a restart to be able to sync again
open /Applications/TogglDesktop.app
open '/Applications/Gmail Notifier.app'

# Activity Watch
# test -z $(pidof aw-qt) && cd && nohup ~/activitywatch/aw-qt &

if [[ "$1" == 'work' ]]; then
	# Desktop 1
	open /Applications/PyCharm.app
	open '/Applications/Visual Studio Code.app/'
	open '/Applications/Mia for Gmail.app'
	open /Applications/Firefox.app
	open /Applications/Skype.app
	open /Applications/Zulip.app

	# Desktop 2
	open /Applications/Spotify.app
	open '/Applications/Spotify Notifications.app'
	open /Applications/Telegram.app
	open /Applications/BeardedSpice.app
	open /Applications/WhatsApp.app

	if [ -f $LAST_WORKING_DIR ]; then
		echo 'Starting Docker VM'
		cd $(cat $LAST_WORKING_DIR)
		docker-find yml cave/do up -d cave
	fi

	exit
fi

if [[ "$1" == 'home' ]]; then
	pwd >$LAST_WORKING_DIR

	echo 'Killing work apps'
	pkill pycharm
	pkill 'Mia for Gmail'
	pkill firefox
	pkill Skype
	pkill Twist
	pkill Spotify
	pkill Telegram
	pkill BeardedSpice
	pkill WhatsApp
	pkill Zulip

	echo 'Stopping EatFirst containers'
    docker-find yml cave/do stop

	echo 'Stopping cli/run-parallel-tests.py containers'
    docker ps -a | rg cave- | awk '{print $1}' | xargs docker rm --force

	exit
fi

echo 'Work or home?'
