#!/bin/bash

LAST_WORKING_DIR=~/.config/clitoolkit/last_working_dir

# Close the browser to force LastPass logout
pkill Brave
sleep 1

# Common
# open '/Applications/Brave Browser.app/'
open /Applications/Dropbox.app
pkill TogglDesktop  # The beta version needs a restart to be able to sync again
open /Applications/TogglDesktop.app
open '/Applications/Gmail Notifier.app'

# Activity Watch
# test -z $(pidof aw-qt) && cd && nohup ~/activitywatch/aw-qt &

# Kill ScanSnap
ps aux | rg scansnap | awk '{print $2}' | xargs kill

if [[ "$1" == 'work' ]]; then
	# Desktop 1
	open /Applications/PyCharm.app
	open '/Applications/Visual Studio Code.app/'
	open '/Applications/Mia for Gmail.app'
	open /Applications/Vivaldi.app/
	open /Applications/Skype.app
	open /Applications/Zulip.app

	# Desktop 2
	open /Applications/Spotify.app
	open '/Applications/Spotify Notifications.app'
	open /Applications/Telegram.app
	open /Applications/BeardedSpice.app
	open /Applications/WhatsApp.app
    open /Applications/Signal.app/

	if [ -f $LAST_WORKING_DIR ]; then
		echo 'Starting Docker VM'
		cd $(cat $LAST_WORKING_DIR)
        docker-find yml cave/do stop
		# docker-find yml cave/do up -d cave
	fi

	exit
fi

if [[ "$1" == 'home' ]]; then
	pwd >$LAST_WORKING_DIR

	echo 'Killing work apps'
	pkill pycharm
	pkill Electron  # Visual Studio Code
	pkill 'Mia for Gmail'
	pkill Vivaldi
	pkill Skype
	pkill Twist
	pkill Spotify
	pkill Telegram
	pkill BeardedSpice
	pkill WhatsApp
	pkill Zulip

    # Kill Signal twice because it's die hard
	sleep .5
    ps aux | rg signal | awk '{print $2}' | xargs kill
	sleep .5
    ps aux | rg signal | awk '{print $2}' | xargs kill

	echo 'Stopping EatFirst containers'
    docker-find yml cave/do stop
    docker-find yml lydia stop

	echo 'Stopping cli/run-parallel-tests.py containers'
    docker ps -a | rg cave- | awk '{print $1}' | xargs docker rm --force

	exit
fi

echo 'Work or home?'
