#!/bin/zsh

LAST_WORKING_DIR=~/.config/clitoolkit/last_working_dir

# Common
open /Applications/Dropbox.app
open /Applications/TogglDesktop.app
open '/Applications/Gmail Notifier.app'

# Activity Watch
test -z $(pidof aw-qt) && nohup ~/activitywatch/aw-qt &

if [[ "$1" == 'work' ]]; then
	defaultbrowser -set firefox

	# Desktop 1
	open /Applications/PyCharm.app
	open '/Applications/Mia for Gmail.app'
	open /Applications/Firefox.app
	open /Applications/Skype.app
	open /Applications/Twist.app

	# Desktop 2
	open /Applications/Spotify.app
	open '/Applications/Spotify Notifications.app'
	open /Applications/Telegram.app
	open /Applications/BeardedSpice.app

	if [ -f $LAST_WORKING_DIR ]; then
		echo 'Starting Docker VM'
		cd $(cat $LAST_WORKING_DIR)
		docker-compose up -d
	fi

	exit
fi

if [[ "$1" == 'home' ]]; then
	pwd >$LAST_WORKING_DIR 
	defaultbrowser -set vivaldi

	echo 'Killing work apps'
	pkill pycharm
	pkill 'Mia for Gmail'
	pkill firefox
	pkill Skype
	pkill Twist
	pkill Spotify
	pkill Telegram
	pkill BeardedSpice

	echo 'Stopping EatFirst containers'
	find ~/eatfirst -name docker-compose.yml -exec docker-compose -f {} stop \;

	exit
fi

echo 'Work or home?'
